### PR TITLE
Update API with events_request class

### PR DESCRIPTION
**Pull request by sparkdevelopment**
@marcincichon Can you check?

### CODE REVIEW

**Comment by marcincichon** [comment]
@sparkdevelopment looks good

**Comment by sparkdevelopment** [comment]
@marcincichon Can you re-review - _should_ be the last commit

**Comment by marcincichon** [comment]
@sparkdevelopment re-reviewed - good to go

**Comment by sparkdevelopment** [comment]
@marcincichon Corrected sort order - can you review?

**Comment by marcincichon** [comment]
@sparkdevelopment looks good

**Pull request merged**
